sudo: false
dist: trusty
language: java
jdk:
  - openjdk8

before_script:
  - if [ ! -d downloads ]; then mkdir downloads; fi;
  - if [ ! -f downloads/vufind-4.0.zip ]; then wget http://downloads.sourceforge.net/vufind/vufind-4.0.zip?use_mirror=osdn -O downloads/vufind-4.0.zip; fi;
  - unzip downloads/vufind-4.0.zip

script:
  - ant test -Dvufind.dir=vufind-4.0

cache:
  directories:
    - downloads
